IF ("${REPOSITORY_NAME}" STREQUAL "")
  SET(REPOSITORY_NAME BootsOnTheGround)
ENDIF()
SET(${REPOSITORY_NAME}_MAJOR_VERSION "0" )
SET(${REPOSITORY_NAME}_VERSION "${${REPOSITORY_NAME}_MAJOR_VERSION}.1")

