botgPackageDependencies(
    LIB_REQUIRED_TPLS
        CURL
    LIB_REQUIRED_PACKAGES
        BootsOnTheGround_ZLIB
        BootsOnTheGround_OPENSSL
    TEST_REQUIRED_PACKAGES
        BootsOnTheGround_GTEST
)
