botgPackageDependencies(
    LIB_REQUIRED_TPLS
        HDF5
    LIB_REQUIRED_PACKAGES
        BootsOnTheGround_ZLIB
        BootsOnTheGround_SZIP
    TEST_REQUIRED_PACKAGES
        BootsOnTheGround_GTEST
)
